services:
  redis:
    image: redis:7.0.11-alpine
  web:
    build:
      context: .
    environment:
      FLASK_APP: run
      FLASK_DEBUG: 1
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0
    ports:
      - 5000:5000
  celery:
    build:
        context: .
    environment:
      FLASK_APP: run
    volumes:
      - .:/app
    command: celery -A run.celery worker --loglevel=info
    depends_on:
      - redis
  flower:
    build:
        context: .
    environment:
      FLASK_APP: run
    volumes:
      - .:/app
    command: celery -A run.celery flower
    depends_on:
      - celery
    ports:
      - 5555:5555

